//=========================================================
// File: app/layout.tsx
// Author: Taemin Lee
// Date: 2025-06-01
//
// Description:
// Root layout for the entire Next.js application using the App Router.
// It sets global font styles, wraps all pages in a consistent layout,
// and applies metadata for SEO.
//
// Features:
// - Registers and applies Google Fonts (`Geist`, `Geist_Mono`)
// - Uses CSS variables for custom font control
// - Applies global styles via `globals.css`
// - Sets HTML structure and base body classes
// - Provides default page title and description via metadata
//
//=========================================================

import type { Metadata } from "next" // Metadata type for SEO settings
import { Geist, Geist_Mono } from "next/font/google" // Google font imports
import "./globals.css" // Global styles applied to all pages

// Load Geist Sans font with a custom CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

// Load Geist Mono font with a custom CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// Global metadata for the app (title, description)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Root layout function that wraps all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode // React children elements (i.e., the page content)
}>) {
  return (
    <html lang="en"> {/* Set document language to English */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Apply font CSS variables and enable antialiasing for smoother fonts */}
        {children} {/* Render the current route's page content */}
      </body>
    </html>
  )
}
